what is pandas? why does it matter?
python library
working with tabular data - data organized in row and column
same like spreadsheet

it can:
load, filter and reshape a table with million rows just as easily as one with ten

Polar
more vast than pandas

Series
one labeled column of data

Dataframe
a table of series sharing same index

In [2]:
import pandas as pd

test_series = pd.Series([2, 3, 4, 5, 6, 7, 8], index=['sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday'])

In [ ]:
test_series

In [ ]:
type(test_series)

In [ ]:
test_series.values

In [12]:
# create a dataframe from list of dictionaries

customer_data = [
    {"customer_id": 1, "orders": 5},
    {"customer_id": 2, "orders": 12},
    {"customer_id": 3, "orders": 2}
]

df = pd.DataFrame(customer_data)


dframe = pd.DataFrame([{"ann",1}], columns=["name", "roll"])

In [ ]:
df

   customer_id  orders
0            1       5
1            2      12
2            3       2

In [13]:
dframe

   name roll
0     1  ann

In [84]:
# load data

df = pd.read_csv("class_scores.csv")
df

,student_id,name,city,subject,marks,attendance_percent,exam_date
0,101,Aarav Sharma,Kathmandu,Python Programming,88,95.0,2026-05-02
1,102,Bibek Thapa,Pokhara,Statistics,72,88.5,2026-05-03
2,103,Chandni Rai,Biratnagar,Python Programming,45,70.0,2026-05-02
3,104,Deepika Gurung,Kathmandu,Machine Learning,91,98.0,2026-05-04
4,105,Esha KC,Lalitpur,Statistics,67,80.0,2026-05-03
5,106,Faisal Khan,Butwal,Python Programming,58,65.0,2026-05-02
6,107,Gita Adhikari,Pokhara,Machine Learning,39,55.0,2026-05-04
7,108,Hari Bahadur,Kathmandu,SQL,82,90.0,2026-05-05
8,109,Isha Shrestha,Lalitpur,Statistics,95,99.0,2026-05-03
9,110,Jeevan Lama,Biratnagar,Python Programming,61,72.0,2026-05-02
10,111,Kabita Basnet,Kathmandu,SQL,74,85.0,2026-05-05
11,112,Lokesh Poudel,Pokhara,Machine Learning,48,60.0,2026-05-04
12,113,Maya Tamang,Butwal,Python Programming,90,96.0,2026-05-02
13,114,Nabin Karki,Kathmandu,Statistics,55,75.0,2026-05-03
14,115,Oshin Magar,Lalitpur,SQL,68,82.0,2026-05-05
15,116,Prakash Yadav,Biratnagar,Machine Learning,77,89.0,2026-05-04
16,117,Queenie Rana,Pokhara,Python Programming,33,50.0,2026-05-02
17,118,Rohit Bista,Kathmandu,Statistics,85,92.0,2026-05-03
18,119,Sabina Ghale,Butwal,SQL,62,78.0,2026-05-05
19,120,Tenzin Sherpa,Lalitpur,Machine Learning,93,97.0,2026-05-04

In [ ]:
df.head()

,student_id,name,city,subject,marks,attendance_percent,exam_date
0,101,Aarav Sharma,Kathmandu,Python Programming,88,95.0,2026-05-02
1,102,Bibek Thapa,Pokhara,Statistics,72,88.5,2026-05-03
2,103,Chandni Rai,Biratnagar,Python Programming,45,70.0,2026-05-02
3,104,Deepika Gurung,Kathmandu,Machine Learning,91,98.0,2026-05-04
4,105,Esha KC,Lalitpur,Statistics,67,80.0,2026-05-03

In [85]:
df1 = pd.read_excel("class_scores_b.xlsx", sheet_name= "class_scores_b", header=1)
df1.head()

ValueError: Excel file format cannot be determined, you must specify an engine manually.

In [20]:
df.shape

(20, 7)

In [21]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   student_id          20 non-null     int64
 1   name                20 non-null     str
 2   city                20 non-null     str
 3   subject             20 non-null     str
 4   marks               20 non-null     int64
 5   attendance_percent  20 non-null     float64
 6   exam_date           20 non-null     str
dtypes: float64(1), int64(2), str(4)
memory usage: 1.2 KB

In [23]:
# selecting columns

df['name']

0       Aarav Sharma
1        Bibek Thapa
2        Chandni Rai
3     Deepika Gurung
4            Esha KC
5        Faisal Khan
6      Gita Adhikari
7       Hari Bahadur
8      Isha Shrestha
9        Jeevan Lama
10     Kabita Basnet
11     Lokesh Poudel
12       Maya Tamang
13       Nabin Karki
14       Oshin Magar
15     Prakash Yadav
16      Queenie Rana
17       Rohit Bista
18      Sabina Ghale
19     Tenzin Sherpa
Name: name, dtype: str

# .loc and .iloc

.loc
selects using the actual index labels or column names
always starts with 0 same as our list index
df.loc[2:5]
slice includes 2, 3, 4, 5

.iloc
selects data from its actual integer
starts with 1 and remove the last integer row
df.iloc[1:4, [1, 2]]
show 1, 2, 3

In [24]:
df.loc[0:4, ["name", "city"]]

             name        city
0    Aarav Sharma   Kathmandu
1     Bibek Thapa     Pokhara
2     Chandni Rai  Biratnagar
3  Deepika Gurung   Kathmandu
4         Esha KC    Lalitpur

In [35]:
df.iloc[0:3, [1, 2]]

           name        city
0  Aarav Sharma   Kathmandu
1   Bibek Thapa     Pokhara
2   Chandni Rai  Biratnagar

In [ ]:
df.loc[0:2, ["name", "city"]]

           name        city
0  Aarav Sharma   Kathmandu
1   Bibek Thapa     Pokhara
2   Chandni Rai  Biratnagar

In [83]:
# condition and filtering

df[(df["marks"] > 50) & (df["attendance_percent" < 80])]

TypeError: '>' not supported between instances of 'str' and 'int'

In [41]:
df

0      True
1      True
2     False
3      True
4      True
5      True
6     False
7      True
8      True
9      True
10     True
11    False
12     True
13     True
14     True
15     True
16    False
17     True
18     True
19     True
Name: marks, dtype: bool

In [59]:
df[(df["city"] == 'Kathmandu') & ((df["subject"] == 'Python Programming') | (df["subject"] == 'Machine Learning'))]

,student_id,name,city,subject,marks,attendance_percent,exam_date
0,101,Aarav Sharma,Kathmandu,Python Programming,88,95.0,2026-05-02
3,104,Deepika Gurung,Kathmandu,Machine Learning,91,98.0,2026-05-04

In [63]:
df.query("city=='Kathmandu' and subject in ['Python Programming', 'Machine Learning']")

,student_id,name,city,subject,marks,attendance_percent,exam_date
0,101,Aarav Sharma,Kathmandu,Python Programming,88,95.0,2026-05-02
3,104,Deepika Gurung,Kathmandu,Machine Learning,91,98.0,2026-05-04

In [ ]:
df.dtypes

student_id              int64
name                      str
city                      str
subject                   str
marks                   int64
attendance_percent    float64
exam_date                 str
dtype: object

In [67]:
# rename column

r_df = df.rename(columns={"marks":"score"})
r_df

,student_id,name,city,subject,score,attendance_percent,exam_date
0,101,Aarav Sharma,Kathmandu,Python Programming,88,95.0,2026-05-02
1,102,Bibek Thapa,Pokhara,Statistics,72,88.5,2026-05-03
2,103,Chandni Rai,Biratnagar,Python Programming,45,70.0,2026-05-02
3,104,Deepika Gurung,Kathmandu,Machine Learning,91,98.0,2026-05-04
4,105,Esha KC,Lalitpur,Statistics,67,80.0,2026-05-03
5,106,Faisal Khan,Butwal,Python Programming,58,65.0,2026-05-02
6,107,Gita Adhikari,Pokhara,Machine Learning,39,55.0,2026-05-04
7,108,Hari Bahadur,Kathmandu,SQL,82,90.0,2026-05-05
8,109,Isha Shrestha,Lalitpur,Statistics,95,99.0,2026-05-03
9,110,Jeevan Lama,Biratnagar,Python Programming,61,72.0,2026-05-02
10,111,Kabita Basnet,Kathmandu,SQL,74,85.0,2026-05-05
11,112,Lokesh Poudel,Pokhara,Machine Learning,48,60.0,2026-05-04
12,113,Maya Tamang,Butwal,Python Programming,90,96.0,2026-05-02
13,114,Nabin Karki,Kathmandu,Statistics,55,75.0,2026-05-03
14,115,Oshin Magar,Lalitpur,SQL,68,82.0,2026-05-05
15,116,Prakash Yadav,Biratnagar,Machine Learning,77,89.0,2026-05-04
16,117,Queenie Rana,Pokhara,Python Programming,33,50.0,2026-05-02
17,118,Rohit Bista,Kathmandu,Statistics,85,92.0,2026-05-03
18,119,Sabina Ghale,Butwal,SQL,62,78.0,2026-05-05
19,120,Tenzin Sherpa,Lalitpur,Machine Learning,93,97.0,2026-05-04

In [ ]:
# adding and modifying columns

df['passed'] = df['marks'] > 40
df

,student_id,name,city,subject,marks,attendance_percent,exam_date,passed
0,101,Aarav Sharma,Kathmandu,Python Programming,88,95.0,2026-05-02,True
1,102,Bibek Thapa,Pokhara,Statistics,72,88.5,2026-05-03,True
2,103,Chandni Rai,Biratnagar,Python Programming,45,70.0,2026-05-02,True
3,104,Deepika Gurung,Kathmandu,Machine Learning,91,98.0,2026-05-04,True
4,105,Esha KC,Lalitpur,Statistics,67,80.0,2026-05-03,True
5,106,Faisal Khan,Butwal,Python Programming,58,65.0,2026-05-02,True
6,107,Gita Adhikari,Pokhara,Machine Learning,39,55.0,2026-05-04,False
7,108,Hari Bahadur,Kathmandu,SQL,82,90.0,2026-05-05,True
8,109,Isha Shrestha,Lalitpur,Statistics,95,99.0,2026-05-03,True
9,110,Jeevan Lama,Biratnagar,Python Programming,61,72.0,2026-05-02,True
10,111,Kabita Basnet,Kathmandu,SQL,74,85.0,2026-05-05,True
11,112,Lokesh Poudel,Pokhara,Machine Learning,48,60.0,2026-05-04,True
12,113,Maya Tamang,Butwal,Python Programming,90,96.0,2026-05-02,True
13,114,Nabin Karki,Kathmandu,Statistics,55,75.0,2026-05-03,True
14,115,Oshin Magar,Lalitpur,SQL,68,82.0,2026-05-05,True
15,116,Prakash Yadav,Biratnagar,Machine Learning,77,89.0,2026-05-04,True
16,117,Queenie Rana,Pokhara,Python Programming,33,50.0,2026-05-02,False
17,118,Rohit Bista,Kathmandu,Statistics,85,92.0,2026-05-03,True
18,119,Sabina Ghale,Butwal,SQL,62,78.0,2026-05-05,True
19,120,Tenzin Sherpa,Lalitpur,Machine Learning,93,97.0,2026-05-04,True

In [70]:
# datatype conversion

df['marks'].dtype

dtype('int64')

In [71]:
df['marks'].astype(str)

0     88
1     72
2     45
3     91
4     67
5     58
6     39
7     82
8     95
9     61
10    74
11    48
12    90
13    55
14    68
15    77
16    33
17    85
18    62
19    93
Name: marks, dtype: str

In [72]:
df['marks'] = df['marks'].astype(str)

In [74]:
df.dtypes

student_id              int64
name                      str
city                      str
subject                   str
marks                     str
attendance_percent    float64
exam_date                 str
passed                   bool
dtype: object

In [78]:
# handling dates
df['exam_date'] = pd.to_datetime(df['exam_date'])

In [81]:
df['exam_date'].dt.date

0     2026-05-02
1     2026-05-03
2     2026-05-02
3     2026-05-04
4     2026-05-03
5     2026-05-02
6     2026-05-04
7     2026-05-05
8     2026-05-03
9     2026-05-02
10    2026-05-05
11    2026-05-04
12    2026-05-02
13    2026-05-03
14    2026-05-05
15    2026-05-04
16    2026-05-02
17    2026-05-03
18    2026-05-05
19    2026-05-04
Name: exam_date, dtype: object

In [82]:
df['exam_date'] > '2026-05-05'

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
Name: exam_date, dtype: bool