what is pandas? why does it matter?
python library
working with tabular data - data organized in row and column
same like spreadsheet

it can:
load, filter and reshape a table with million rows just as easily as one with ten

Polar
more vast than pandas

Series
one labeled column of data

Dataframe
a table of series sharing same index

In [2]:
import pandas as pd

test_series = pd.Series([2, 3, 4, 5, 6, 7, 8], index=['sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday'])

In [ ]:
test_series

In [ ]:
type(test_series)

In [ ]:
test_series.values

In [ ]:
# create a dataframe from list of dictionaries

customer_data = [
    {"customer_id": 1, "orders": 5},
    {"customer_id": 2, "orders": 12},
    {"customer_id": 3, "orders": 2}
]

df = pd.DataFrame(customer_data)


dframe = pd.DataFrame([{"ann",1}], columns=["name", "roll"])

In [ ]:
df

   customer_id  orders
0            1       5
1            2      12
2            3       2

In [13]:
dframe

   name roll
0     1  ann

In [84]:
# load data

df = pd.read_csv("class_scores.csv")
df

,student_id,name,city,subject,marks,attendance_percent,exam_date
0,101,Aarav Sharma,Kathmandu,Python Programming,88,95.0,2026-05-02
1,102,Bibek Thapa,Pokhara,Statistics,72,88.5,2026-05-03
2,103,Chandni Rai,Biratnagar,Python Programming,45,70.0,2026-05-02
3,104,Deepika Gurung,Kathmandu,Machine Learning,91,98.0,2026-05-04
4,105,Esha KC,Lalitpur,Statistics,67,80.0,2026-05-03
5,106,Faisal Khan,Butwal,Python Programming,58,65.0,2026-05-02
6,107,Gita Adhikari,Pokhara,Machine Learning,39,55.0,2026-05-04
7,108,Hari Bahadur,Kathmandu,SQL,82,90.0,2026-05-05
8,109,Isha Shrestha,Lalitpur,Statistics,95,99.0,2026-05-03
9,110,Jeevan Lama,Biratnagar,Python Programming,61,72.0,2026-05-02
10,111,Kabita Basnet,Kathmandu,SQL,74,85.0,2026-05-05
11,112,Lokesh Poudel,Pokhara,Machine Learning,48,60.0,2026-05-04
12,113,Maya Tamang,Butwal,Python Programming,90,96.0,2026-05-02
13,114,Nabin Karki,Kathmandu,Statistics,55,75.0,2026-05-03
14,115,Oshin Magar,Lalitpur,SQL,68,82.0,2026-05-05
15,116,Prakash Yadav,Biratnagar,Machine Learning,77,89.0,2026-05-04
16,117,Queenie Rana,Pokhara,Python Programming,33,50.0,2026-05-02
17,118,Rohit Bista,Kathmandu,Statistics,85,92.0,2026-05-03
18,119,Sabina Ghale,Butwal,SQL,62,78.0,2026-05-05
19,120,Tenzin Sherpa,Lalitpur,Machine Learning,93,97.0,2026-05-04

In [ ]:
df.head()

,student_id,name,city,subject,marks,attendance_percent,exam_date
0,101,Aarav Sharma,Kathmandu,Python Programming,88,95.0,2026-05-02
1,102,Bibek Thapa,Pokhara,Statistics,72,88.5,2026-05-03
2,103,Chandni Rai,Biratnagar,Python Programming,45,70.0,2026-05-02
3,104,Deepika Gurung,Kathmandu,Machine Learning,91,98.0,2026-05-04
4,105,Esha KC,Lalitpur,Statistics,67,80.0,2026-05-03

In [85]:
df1 = pd.read_excel("class_scores_b.xlsx", sheet_name= "class_scores_b", header=1)
df1.head()

ValueError: Excel file format cannot be determined, you must specify an engine manually.

In [20]:
df.shape

(20, 7)

In [21]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   student_id          20 non-null     int64
 1   name                20 non-null     str
 2   city                20 non-null     str
 3   subject             20 non-null     str
 4   marks               20 non-null     int64
 5   attendance_percent  20 non-null     float64
 6   exam_date           20 non-null     str
dtypes: float64(1), int64(2), str(4)
memory usage: 1.2 KB

In [23]:
# selecting columns

df['name']

0       Aarav Sharma
1        Bibek Thapa
2        Chandni Rai
3     Deepika Gurung
4            Esha KC
5        Faisal Khan
6      Gita Adhikari
7       Hari Bahadur
8      Isha Shrestha
9        Jeevan Lama
10     Kabita Basnet
11     Lokesh Poudel
12       Maya Tamang
13       Nabin Karki
14       Oshin Magar
15     Prakash Yadav
16      Queenie Rana
17       Rohit Bista
18      Sabina Ghale
19     Tenzin Sherpa
Name: name, dtype: str

# .loc and .iloc

.loc
selects using the actual index labels or column names
always starts with 0 same as our list index
df.loc[2:5]
slice includes 2, 3, 4, 5

.iloc
selects data from its actual integer
starts with 1 and remove the last integer row
df.iloc[1:4, [1, 2]]
show 1, 2, 3

In [24]:
df.loc[0:4, ["name", "city"]]

             name        city
0    Aarav Sharma   Kathmandu
1     Bibek Thapa     Pokhara
2     Chandni Rai  Biratnagar
3  Deepika Gurung   Kathmandu
4         Esha KC    Lalitpur

In [35]:
df.iloc[0:3, [1, 2]]

           name        city
0  Aarav Sharma   Kathmandu
1   Bibek Thapa     Pokhara
2   Chandni Rai  Biratnagar

In [ ]:
df.loc[0:2, ["name", "city"]]

           name        city
0  Aarav Sharma   Kathmandu
1   Bibek Thapa     Pokhara
2   Chandni Rai  Biratnagar

In [83]:
# condition and filtering

df[(df["marks"] > 50) & (df["attendance_percent" < 80])]

TypeError: '>' not supported between instances of 'str' and 'int'

In [41]:
df

0      True
1      True
2     False
3      True
4      True
5      True
6     False
7      True
8      True
9      True
10     True
11    False
12     True
13     True
14     True
15     True
16    False
17     True
18     True
19     True
Name: marks, dtype: bool

In [59]:
df[(df["city"] == 'Kathmandu') & ((df["subject"] == 'Python Programming') | (df["subject"] == 'Machine Learning'))]

,student_id,name,city,subject,marks,attendance_percent,exam_date
0,101,Aarav Sharma,Kathmandu,Python Programming,88,95.0,2026-05-02
3,104,Deepika Gurung,Kathmandu,Machine Learning,91,98.0,2026-05-04

In [63]:
df.query("city=='Kathmandu' and subject in ['Python Programming', 'Machine Learning']")

,student_id,name,city,subject,marks,attendance_percent,exam_date
0,101,Aarav Sharma,Kathmandu,Python Programming,88,95.0,2026-05-02
3,104,Deepika Gurung,Kathmandu,Machine Learning,91,98.0,2026-05-04

In [ ]:
df.dtypes

student_id              int64
name                      str
city                      str
subject                   str
marks                   int64
attendance_percent    float64
exam_date                 str
dtype: object

In [67]:
# rename column

r_df = df.rename(columns={"marks":"score"})
r_df

,student_id,name,city,subject,score,attendance_percent,exam_date
0,101,Aarav Sharma,Kathmandu,Python Programming,88,95.0,2026-05-02
1,102,Bibek Thapa,Pokhara,Statistics,72,88.5,2026-05-03
2,103,Chandni Rai,Biratnagar,Python Programming,45,70.0,2026-05-02
3,104,Deepika Gurung,Kathmandu,Machine Learning,91,98.0,2026-05-04
4,105,Esha KC,Lalitpur,Statistics,67,80.0,2026-05-03
5,106,Faisal Khan,Butwal,Python Programming,58,65.0,2026-05-02
6,107,Gita Adhikari,Pokhara,Machine Learning,39,55.0,2026-05-04
7,108,Hari Bahadur,Kathmandu,SQL,82,90.0,2026-05-05
8,109,Isha Shrestha,Lalitpur,Statistics,95,99.0,2026-05-03
9,110,Jeevan Lama,Biratnagar,Python Programming,61,72.0,2026-05-02
10,111,Kabita Basnet,Kathmandu,SQL,74,85.0,2026-05-05
11,112,Lokesh Poudel,Pokhara,Machine Learning,48,60.0,2026-05-04
12,113,Maya Tamang,Butwal,Python Programming,90,96.0,2026-05-02
13,114,Nabin Karki,Kathmandu,Statistics,55,75.0,2026-05-03
14,115,Oshin Magar,Lalitpur,SQL,68,82.0,2026-05-05
15,116,Prakash Yadav,Biratnagar,Machine Learning,77,89.0,2026-05-04
16,117,Queenie Rana,Pokhara,Python Programming,33,50.0,2026-05-02
17,118,Rohit Bista,Kathmandu,Statistics,85,92.0,2026-05-03
18,119,Sabina Ghale,Butwal,SQL,62,78.0,2026-05-05
19,120,Tenzin Sherpa,Lalitpur,Machine Learning,93,97.0,2026-05-04

In [ ]:
# adding and modifying columns

df['passed'] = df['marks'] > 40
df

,student_id,name,city,subject,marks,attendance_percent,exam_date,passed
0,101,Aarav Sharma,Kathmandu,Python Programming,88,95.0,2026-05-02,True
1,102,Bibek Thapa,Pokhara,Statistics,72,88.5,2026-05-03,True
2,103,Chandni Rai,Biratnagar,Python Programming,45,70.0,2026-05-02,True
3,104,Deepika Gurung,Kathmandu,Machine Learning,91,98.0,2026-05-04,True
4,105,Esha KC,Lalitpur,Statistics,67,80.0,2026-05-03,True
5,106,Faisal Khan,Butwal,Python Programming,58,65.0,2026-05-02,True
6,107,Gita Adhikari,Pokhara,Machine Learning,39,55.0,2026-05-04,False
7,108,Hari Bahadur,Kathmandu,SQL,82,90.0,2026-05-05,True
8,109,Isha Shrestha,Lalitpur,Statistics,95,99.0,2026-05-03,True
9,110,Jeevan Lama,Biratnagar,Python Programming,61,72.0,2026-05-02,True
10,111,Kabita Basnet,Kathmandu,SQL,74,85.0,2026-05-05,True
11,112,Lokesh Poudel,Pokhara,Machine Learning,48,60.0,2026-05-04,True
12,113,Maya Tamang,Butwal,Python Programming,90,96.0,2026-05-02,True
13,114,Nabin Karki,Kathmandu,Statistics,55,75.0,2026-05-03,True
14,115,Oshin Magar,Lalitpur,SQL,68,82.0,2026-05-05,True
15,116,Prakash Yadav,Biratnagar,Machine Learning,77,89.0,2026-05-04,True
16,117,Queenie Rana,Pokhara,Python Programming,33,50.0,2026-05-02,False
17,118,Rohit Bista,Kathmandu,Statistics,85,92.0,2026-05-03,True
18,119,Sabina Ghale,Butwal,SQL,62,78.0,2026-05-05,True
19,120,Tenzin Sherpa,Lalitpur,Machine Learning,93,97.0,2026-05-04,True

In [70]:
# datatype conversion

df['marks'].dtype

dtype('int64')

In [71]:
df['marks'].astype(str)

0     88
1     72
2     45
3     91
4     67
5     58
6     39
7     82
8     95
9     61
10    74
11    48
12    90
13    55
14    68
15    77
16    33
17    85
18    62
19    93
Name: marks, dtype: str

In [72]:
df['marks'] = df['marks'].astype(str)

In [74]:
df.dtypes

student_id              int64
name                      str
city                      str
subject                   str
marks                     str
attendance_percent    float64
exam_date                 str
passed                   bool
dtype: object

In [78]:
# handling dates
df['exam_date'] = pd.to_datetime(df['exam_date'])

In [81]:
df['exam_date'].dt.date

0     2026-05-02
1     2026-05-03
2     2026-05-02
3     2026-05-04
4     2026-05-03
5     2026-05-02
6     2026-05-04
7     2026-05-05
8     2026-05-03
9     2026-05-02
10    2026-05-05
11    2026-05-04
12    2026-05-02
13    2026-05-03
14    2026-05-05
15    2026-05-04
16    2026-05-02
17    2026-05-03
18    2026-05-05
19    2026-05-04
Name: exam_date, dtype: object

In [ ]:
df['exam_date'] > '2026-05-05'

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
Name: exam_date, dtype: bool

In [1]:
import pandas as pd
import numpy as np

In [27]:
# create a pandas dataframe

d = {
    'first_score': [100, 90, np.nan, 34],
    'second_score': [30, 20, np.nan, 20],
    'third_score': [np.nan, 40, 80, 98]
}

df = pd.DataFrame(d)
df

   first_score  second_score  third_score
0        100.0          30.0          NaN
1         90.0          20.0         40.0
2          NaN           NaN         80.0
3         34.0          20.0         98.0

In [ ]:
df.isnull()

   first_score  second_score  third_score
0        False         False         True
1        False         False        False
2         True          True        False
3        False         False        False

In [5]:
df.isnull().sum()

first_score     1
second_score    1
third_score     1
dtype: int64

In [10]:
bool_series = pd.isnull(df["first_score"])
df[bool_series]

   first_score  second_score  third_score
2          NaN           NaN         80.0

In [11]:
df.notnull()

   first_score  second_score  third_score
0         True          True        False
1         True          True         True
2        False         False         True
3         True          True         True

In [13]:
nmv = pd.notnull(df["first_score"])
df[nmv]

   first_score  second_score  third_score
0        100.0          30.0          NaN
1         90.0          20.0         40.0
3         34.0          20.0         98.0

In [ ]:
# to fill missing value

df.ffill()

   first_score  second_score  third_score
0        100.0          30.0          NaN
1         90.0          20.0         40.0
2         90.0          20.0         80.0
3         34.0          20.0         98.0

In [16]:
# backward fill
df.bfill()

   first_score  second_score  third_score
0        100.0          30.0         40.0
1         90.0          20.0         40.0
2         34.0          20.0         80.0
3         34.0          20.0         98.0

In [19]:
df["second_score"].fillna(25)

0    30.0
1    20.0
2    25.0
3    20.0
Name: second_score, dtype: float64

In [20]:
df

   first_score  second_score  third_score
0        100.0          30.0          NaN
1         90.0          20.0         40.0
2          NaN           NaN         80.0
3         34.0          20.0         98.0

In [21]:
# make change in the actual table

df["second_score"].fillna(25)

0    30.0
1    20.0
2    25.0
3    20.0
Name: second_score, dtype: float64

In [22]:
df["second_score"] = df["second_score"].fillna(25)

In [23]:
df

   first_score  second_score  third_score
0        100.0          30.0          NaN
1         90.0          20.0         40.0
2          NaN          25.0         80.0
3         34.0          20.0         98.0

In [ ]:
# using replace

data = df["second_score"].replace()

In [ ]:
# dropping missing values in rows

df.dropna()

   first_score  second_score  third_score
1         90.0          20.0         40.0
3         34.0          20.0         98.0

In [29]:
df

   first_score  second_score  third_score
0        100.0          30.0          NaN
1         90.0          20.0         40.0
2          NaN           NaN         80.0
3         34.0          20.0         98.0

In [28]:
df.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

In [34]:

d = {
    'first_score': [np.nan, np.nan, np.nan, 20],
    'second_score': [30, 2, 10, 20],
    'third_score': [np.nan, np.nan, np.nan, 20]
}

df = pd.DataFrame(d)
df.dropna(axis=1)

   second_score
0            30
1             2
2            10
3            20

In [32]:
df[df.duplicated()]

Empty DataFrame
Columns: [first_score, second_score, third_score]
Index: []

In [ ]:
df.sort_values("Name", implace=True)

TypeError: DataFrame.sort_values() got an unexpected keyword argument 'implace'

In [ ]:
bool_series = df["Name"].duplicated(keep=True)
bool_series

In [ ]:
bool_series = df["Name"].duplicated(keep='last')
bool_series
data = df[~bool_series]
data

In [ ]:
df= pd.DataFrame(
    {
        "Name": ['Alice ', "Bob ", "Alice ", "Charlie "],
        'Age': [25, 32, 25, 37]
    }
)
df['Name'].str.upper()

0      ALICE
1        BOB
2      ALICE
3    CHARLIE
Name: Name, dtype: str

In [45]:
df= pd.DataFrame(
    {
        "Name": ['Al ice ', "Bob ", "Alice ", "Charlie "],
        'Age': [25, 32, 25, 37]
    }
)
df["Name"].str.rstrip()

0     Al ice
1        Bob
2      Alice
3    Charlie
Name: Name, dtype: str

In [46]:
# separate name into list in tow parts using i as separator

df= pd.DataFrame(
    {
        "Name": ['Al ice ', "Bob ", "Alice ", "Charlie "],
        'Age': [25, 32, 25, 37]
    }
)
df["Name"].str.split('i')

0     [Al , ce ]
1         [Bob ]
2      [Al, ce ]
3    [Charl, e ]
Name: Name, dtype: object

In [47]:
df= pd.DataFrame(
    {
        "Name": ['Al ice ', "Bob ", "Alice ", "Charlie "],
        'Age': [25, 32, 25, 37]
    }
)
df["Name"].str.len()

0    7
1    4
2    6
3    8
Name: Name, dtype: int64

In [ ]:
df['Name'].int_dummies

In [48]:
# replace
df['Name'] = df['Name'].str.replace('heo')

TypeError: repl must be a string or callable

In [50]:
df = pd.DataFrame(
    {
        'price': [100, 200, 300],
        "quantity": [2, 3, 4]
    }
)
df

   price  quantity
0    100         2
1    200         3
2    300         4

In [51]:
df['price'] = df['price'] / 10
df

   price  quantity
0   10.0         2
1   20.0         3
2   30.0         4

In [53]:
df['total'] = df['price'] * df['quantity']
df

   price  quantity  total
0   10.0         2   20.0
1   20.0         3   60.0
2   30.0         4  120.0

In [54]:
df['discounted_price'] = df['total'] * 0.9
df

   price  quantity  total  discounted_price
0   10.0         2   20.0              18.0
1   20.0         3   60.0              54.0
2   30.0         4  120.0             108.0

In [55]:
# aggregation
# sum(), mean(), median(), max(), min(), std(), var()
df['total'].sum()

np.float64(200.0)

In [56]:
df['total'].max()

np.float64(120.0)

In [58]:
df['total'].min()

np.float64(20.0)

In [59]:
# axis = 0,  row
# axis = 0 , column

In [60]:
df.sum(axis=0)

price                60.0
quantity              9.0
total               200.0
discounted_price    180.0
dtype: float64

In [61]:
df.sum(axis=1)

0     50.0
1    137.0
2    262.0
dtype: float64

In [62]:
df['price'] > 120

0    False
1    False
2    False
Name: price, dtype: bool

In [63]:
# < , > , == , <= , >= , !=

In [65]:
df[(df['price'] > 20) & (df['quantity'] > 2)]

   price  quantity  total  discounted_price
2   30.0         4  120.0             108.0

In [66]:
# & | ~

In [69]:
# .round(2) , floor()
df['price'].round(5)

0    10.0
1    20.0
2    30.0
Name: price, dtype: float64

In [70]:
df['price'].fillna(df['price'].mean())

0    10.0
1    20.0
2    30.0
Name: price, dtype: float64

In [74]:
# date time conversions

df = pd.DataFrame(
    {
        'date': [
            "2026-01-15",
            "2026-02-20",
            "2026-03-10"
        ]
    }
)
df

         date
0  2026-01-15
1  2026-02-20
2  2026-03-10

In [72]:
df['date'].dtype

In [76]:
df['date'] = pd.to_datetime(df['date'])
df['date'].dtype

dtype('<M8[us]')

In [79]:
df['date'] = pd.to_datetime(
    df['date'],
    format=  "%Y-%M-%D"
)
df['date']

0   2026-01-15
1   2026-02-20
2   2026-03-10
Name: date, dtype: datetime64[us]

In [84]:
df['day'] = df['date'].dt.day_of_week
df['day']

0    3
1    4
2    1
Name: day, dtype: int32

In [86]:
df['weekday'] = df['date'].dt.weekday
df

        date  day  weekday
0 2026-01-15    3        3
1 2026-02-20    4        4
2 2026-03-10    1        1

In [87]:
# to string
df['date_string'] = df['date'].dt.strftime('%y-%m-%d')
df

        date  day  weekday date_string
0 2026-01-15    3        3    26-01-15
1 2026-02-20    4        4    26-02-20
2 2026-03-10    1        1    26-03-10

In [88]:
df[
    (df["date"] >= "2026-01-20")
]

        date  day  weekday date_string
1 2026-02-20    4        4    26-02-20
2 2026-03-10    1        1    26-03-10

In [89]:
# aggregation date to summarize trends in pandas

df = pd.DataFrame(
    {
        "product": ["A", "A", "B", "B", "C"],
        "sales": [100, 150, 200, 250, 300],
        "quantity": [2, 3, 4, 5, 6]
    }
)

In [90]:
df['sales'].sum()

np.int64(1000)

In [91]:
# calculate slaes for each product
# groupby
df.groupby("product")["sales"].sum()

product
A    250
B    450
C    300
Name: sales, dtype: int64

In [92]:
# multiple aggregation

df.groupby("product")["sales"].agg(
    [
        "sum",
        "mean",
        "min",
        "max"
    ]
)

         sum   mean  min  max
product
A        250  125.0  100  150
B        450  225.0  200  250
C        300  300.0  300  300

In [94]:
df.groupby("product").agg(
    {
        "sales": ["sum", "min", "max"],
        "quantity": "sum"
    }
    
)

        sales           quantity
          sum  min  max      sum
product
A         250  100  150        5
B         450  200  250        9
C         300  300  300        6

In [95]:
df.groupby("product").agg(
    total_sales = ("sales", "sum"),
    average_sales = ("sales", "min")
)

         total_sales  average_sales
product
A                250            100
B                450            200
C                300            300

In [96]:
df.groupby("product").size()

product
A    2
B    2
C    1
dtype: int64

In [98]:
df.groupby('product')['sales'].count()

product
A    2
B    2
C    1
Name: sales, dtype: int64

In [105]:
df = pd.DataFrame(
    {
        'date': [
            "2026-01-15",
            "2026-01-15",
            "2026-02-20",
            "2026-03-10"
        ],
    "sales": [120, 100, 150, 200]
    },
)

df['date'] = pd.to_datetime(df['date'])

In [107]:
df.groupby('date')['sales'].sum()

date
2026-01-15    220
2026-02-20    150
2026-03-10    200
Name: sales, dtype: int64

In [110]:
df['month'] = df['date'].dt.to_period('M')
df

        date  sales    month
0 2026-01-15    120  2026-01
1 2026-01-15    100  2026-01
2 2026-02-20    150  2026-02
3 2026-03-10    200  2026-03

In [113]:
df = pd.DataFrame(
    {
        "region": ["East", "East", "West", "West"],
        "product": ["A", "B", "A", "B"],
        "sales": [100, 200, 150, 300]
    }
)

df.groupby(["region", "product"])["sales"].sum()

region  product
East    A          100
        B          200
West    A          150
        B          300
Name: sales, dtype: int64

In [114]:
pd.pivot_table(
    df,
    values="sales",
    index="region",
    columns="product",
    aggfunc="sum"
)

product    A    B
region
East     100  200
West     150  300

In [116]:
# aggrigation vs transformation

df.groupby('product')['sales'].mean()

product
A    125.0
B    250.0
Name: sales, dtype: float64

In [ ]:
# group by category and time in pandas
df.groupby(['category', 'time'])['values'].agg(...)